module.exports = {

  //EVENTS STORE
  SHOW_EVENTS: 'SHOW_EVENTS',
  LOAD_EVENTS: 'LOAD_EVENTS',
  LOAD_EVENTS_INVITEES: 'LOAD_EVENTS_INVITEES',
  LOAD_EVENTS_SUCCESS: 'LOAD_EVENTS_SUCCESS',
  LOAD_EVENTS_FAIL: 'LOAD_EVENTS_FAIL',
  LOAD_EVENTS_ORDER_SUCCESS: 'LOAD_EVENTS_ORDER_SUCCESS',
  CREATE_EVENT: 'CREATE_EVENT',
  CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
  CREATE_EVENT_FAIL: 'CREATE_EVENT_FAIL',

  //FRIENDS STORE
  SHOW_FRIENDS: 'SHOW_FRIENDS',
  ADD_FRIEND: 'ADD_FRIEND', 
  LOAD_FRIENDS: 'LOAD_FRIENDS',
  LOAD_FRIENDS_SUCCESS: 'LOAD_FRIENDS_SUCCESS',
  LOAD_FRIENDS_FAIL: 'LOAD_FRIENDS_FAIL',

  //MESSAGES STORE
  LOAD_MESSAGES: 'LOAD_MESSAGES',
  LOAD_MESSAGES_SUCCESS: 'LOAD_MESSAGES_SUCCESS',
  LOAD_MESSAGES_FAIL: 'LOAD_MESSAGES_FAIL',
  CREATE_MESSAGE: 'CREATE_MESSAGE',
  CREATE_MESSAGE_SUCCESS: 'CREATE_MESSAGE_SUCCESS',
  CREATE_MESSAGE_FAIL: 'CREATE_MESSAGE_FAIL',
  GET_TEXT_INPUT: 'GET_TEXT_INPUT'
};
