module.exports = {
  SHOW_EVENTS: "SHOW_EVENTS",
  DELETE_EVENT: "DELETE_EVENT",
  CREATE_EVENT: "CREATE_EVENT",
  EDIT_EVENT: "EDIT_EVENT",
  LOG_INFO: "LOG_INFO",
  SHOW_FRIENDS: "SHOW_FRIENDS",
  ADD_FRIEND: "ADD_FRIEND", 
  LOAD_FRIENDS: "LOAD_FRIENDS",
  LOAD_FRIENDS_SUCCESS: "LOAD_FRIENDS_SUCCESS",
  LOAD_FRIENDS_FAIL: "LOAD_FRIENDS_FAIL"
};
